### ISSUE TITLE
Order categories appropriately on homepage

### ISSUE THREAD

**Issue by millzpaugh** [codeforamerica/syracuse_biz_portal#17]

**Comment by cweems** [comment]
@millzpaugh I think that this was resolved when you made the homepage dynamic! See here: https://github.com/codeforamerica/syracuse_biz_portal/blob/master/home/templates/home/home_page.html#L30

Although definitely possible I'm misunderstanding this issue.

**Comment by millzpaugh** [comment]
This actually isn't resolved yet - we still don't have a way to choose how categories are ordered on the homepage, nav, or elsewhere. (ie Plan = 1st, Launch = 2nd, Grow = 3rd). We could just add an order_num field, but I'm open to other options!
